### ISSUE TITLE
Unable to open management interface

### ISSUE THREAD

**Issue by yesimxev** [Vudentz/BlueZ#2]
Looks like bluetoothd is unable to start on armhf. also tried btmgm command which results in:
`Unable to open mgmt_socket`
Looking at strace, there is something wrong with the hci channel:
```
socket(AF_BLUETOOTH, SOCK_RAW|SOCK_CLOEXEC|SOCK_NONBLOCK, BTPROTO_HCI) = 4 
bind(4, {sa_family=AF_BLUETOOTH, hci_dev=htobs(65535), hci_channel=HCI_CHANNEL_CONTROL}, 6) = -1 EINVAL (Invalid argument)
```
Kernel is above 3.4 too so should be compatible. I feel i have a software related setting missing

**Comment by Flohack74** [comment]
I have a similar thing here:
`socket(PF_BLUETOOTH, SOCK_RAW|SOCK_CLOEXEC|SOCK_NONBLOCK, 1) = 7
bind(7, {sa_family=AF_BLUETOOTH, sa_data="\377\377\3\0\0\0\0\0\0\0\0\0\0\0"}, 6) = -1 EINVAL (Invalid argument)
close(7) `

**Comment by yesimxev** [comment]
Yes bluez 4.1xx does the job for this older device

**Comment by yesimxev** [comment]
Most of the devices support bluez5 so this is a kernel related issue. Closing for now

**Comment by Flohack74** [comment]
Ok the problem was that Android has messed the kernel completely up with reverting stuff from Mainline, which then broke Bluez 5.41

**Comment by RockYou-cmd** [comment]
> Looks like bluetoothd is unable to start on armhf. also tried btmgm command which results in: `Unable to open mgmt_socket` Looking at strace, there is something wrong with the hci channel:
> 
> ```
> socket(AF_BLUETOOTH, SOCK_RAW|SOCK_CLOEXEC|SOCK_NONBLOCK, BTPROTO_HCI) = 4 
> bind(4, {sa_family=AF_BLUETOOTH, hci_dev=htobs(65535), hci_channel=HCI_CHANNEL_CONTROL}, 6) = -1 EINVAL (Invalid argument)
> ```
> 
> Kernel is above 3.4 too so should be compatible. I feel i have a software related setting missing

hello man, how to fix `Unable to open mgmt_socket` problem

**Comment by yesimxev** [comment]
Downgrade to bluez 4.101, build from source and install without removing the old one whoch was installed with apt
